export const UPDATE_QUESTION1 = 'UPDATE_QUESTION1';
export const UPDATE_QUESTION2 = 'UPDATE_QUESTION2';
export const UPDATE_PLAYZONE = 'UPDATE_PLAYZONE';
export const UPDATE_AGE = 'UPDATE_AGE';
export const UPDATE_ANNUAL_INCOME = 'UPDATE_ANNUAL_INCOME';
export const UPDATE_TOTAL_ANNUAL_CONTRIBUTION = 'UPDATE_TOTAL_ANNUAL_CONTRIBUTION';
export const UPDATE_PERCENTAGE_COMPLETE = 'UPDATE_PERCENTAGE_COMPLETE';